### ISSUE TITLE
Kill `form--small`?

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#162]
I don't think we have ever used this. (I checked the app.) Let's delete it?

```scss
.#{$namespace}form--small {
  font-size: map-fetch($font, size micro);
}
```

cc: @tomgenoni
