### ISSUE TITLE
Improve the `map-fetch` function

### ISSUE THREAD

**Issue by HugoGiraudel** [optimizely/oui#239]
Ohai.

I’d like to submit a few recommendations for your `map-fetch` function:

- The name `map-fetch` probably comes from me. I used to call this function like this a while back, and I guess it kind of stuck… Meanwhile, it is not a great name; `map-deep-get` makes more sense for most people. I’d recommend you name it this way.
- A `map-deep-get` function is by definition variadic, and therefore is the perfect candidate for an arguments list rather than an actual list. It makes it plain obvious that any number of keys can be passed as arguments.
- I fear you have gone a bit over-complex in your current implementation, and I would like to propose a new, dramatically simplified one.

```scss
@function map-deep-get($map, $keys...) {
  @each $key in $keys {
    $map: map-get($map, $key);
    
    @if not $map {
      @error 'The value `#{$key}` doesn’t exist in the map.';
    }
  }
  
  @return $map;
}
```

Best. :)
