### ISSUE TITLE
Display mixin is obsolete

### ISSUE THREAD

**Issue by HugoGiraudel** [optimizely/oui#241]
Display mixin: https://github.com/optimizely/oui/blob/devel/src/oui/partials/elements/_flexbox.scss#L22-L26.

```scss
@mixin display($value) {
  display: -webkit-#{$value};
  display: -ms-#{$value}box;
  display: $value;
}
```

As far as I can tell, there is something wrong here. Either you want the `display(..)` mixin to be a wrapper around the `display` CSS property, and there is no reason to output WebKit and Microsoft specific variations without checking for the `flex` value. Or you want this to be a helper to initialize a flex container —which seems like given the filename, the code comments and the `box` suffix on line 3— and you don’t need an argument at all.

```scss
@mixin flex-container {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```
