### ISSUE TITLE
Flex mixin is likely to break

### ISSUE THREAD

**Issue by HugoGiraudel** [optimizely/oui#242]
Flex mixin: https://github.com/optimizely/oui/blob/devel/src/oui/partials/elements/_flexbox.scss#L28-L35.

The condition in the `flex` mixin is likely to break. `$num != '0'` will evaluate to true even if you pass `0` as a number, which is not what you want. Either you need to cast the parameter to a string (which I would not necessarily recommend), or you need to also check for the numeric version of the value (if there is).

```scss
@mixin flex($num) {
  -webkit-flex: $num;
  -ms-flex: $num;
  flex: $num;
  @if ($num != '0' and $num != 0) { // http://stackoverflow.com/questions/29398259/css-flexbox-issue-in-firefox-v36-and-greater
    min-height: 0;
    min-width: 0;
  }
}
```
